apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-replacer-secret
data:
#   sample-secret: <secret:secret/data/devwebapp/config~password|base64>
  sample-secret: <secret:argocd/data/example~key123|base64>
type: Opaque
